name: hive_benchmark

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.1.0
  path: ^1.6.4
  random_string: ^1.1.0
  hive: ^0.4.0
  sqflite: ^1.3.0+1
  shared_preferences: ^0.5.7+2
  fl_chart: ^0.3.3
  moor_ffi: ^0.5.0
  sembast: ^2.4.3

flutter:
  uses-material-design: true